language: python
Python: 3.6
sudo: false
dist: trusty

matrix:
  include:
    - os: linux
      addons: &1
        apt:
          packages:
            - g++
      env:
        - BUILD_TYPE='release'
        - CXX_COMPILER='g++'
    - os: linux
      addons: *1
      env:
        - BUILD_TYPE='debug'
        - CXX_COMPILER='g++'

env:
  global:
    - LC_ALL="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - LANGUAGE="en_US.UTF-8"
    - PYTHONIOENCODING=UTF-8
    - OMP_NUM_THREADS=1
    - CMAKE_VERSION="3.12.1"

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Deps/cmake/$CMAKE_VERSION
    - $HOME/Deps/eigen

before_install:
  # Dependencies are downloaded in $HOME/Downloads and installed in $HOME/Deps
  - mkdir -p $HOME/Downloads $HOME/Deps

install:
  - ./.ci/cmake.sh
  - export PATH=$HOME/Deps/cmake/$CMAKE_VERSION/bin${PATH:+:$PATH}
  - ./.ci/eigen.sh

before_script:
  - test -n $CXX && unset CXX

script:
  - ./.ci/report_versions.sh
  - |
    python ./setup \
           --type=${BUILD_TYPE} \
           --prefix=$HOME/Software/VAMPyR \
           --cxx=${CXX_COMPILER} \
           ${OPENMP} \
           --cmake-options="-DEigen3_DIR=${HOME}/Deps/eigen/share/eigen3/cmake"
  - cmake --build build --target install -- VERBOSE=1
  - cd build
  - ctest --output-on-failure --verbose

