[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "vampyr"
authors = [{name = "Magnar Bjørgve", email = "magnar.bjorgve@uit.no"}]
dynamic = ["version", "description"]
