name: Install VAMPyR with pip

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pip install
      run: |
        python -m pip install -vvv .[test]

    - name: Import VAMPyR
      run: |
        python -c "import vampyr; print(vampyr.__version__); print(vampyr.mrcpp_version())"

    - name: Test with pytest
      run: |
        python -m pytest -rws -v --pyargs vampyr
